#!/bin/bash

name="$(cat /etc/os-release | grep -Eo "^NAME=\"[^\"]+\"" | sed -e 's/^.*="//' -e 's/"$//')"
if [[ $name == "Ubuntu" ]]; then
  service apache2 start
elif [[ $name == "Amazon Linux AMI" ]]; then
  service httpd start
else
  printf "Distribution ${name} is not supported yet.\n"  
fi
