#!/bin/bash

name="$(cat /etc/os-release | grep -Eo "^NAME=\"[^\"]+\"" | sed -e 's/^.*="//' -e 's/"$//')"
if [[ ${name} == "Ubuntu" ]]; then
  isExistApp=`pgrep apache2`
  if [[ -n  $isExistApp ]]; then
    service apache2 stop        
  fi
elif [[ ${name} == "Amazon Linux AMI" ]]; then
  isExistApp=`pgrep httpd`
  if [[ -n  $isExistApp ]]; then
    service httpd stop        
  fi
else
  printf "Distribution ${name} is not supported yet.\n"  
fi